/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP DATABASE IF EXISTS `TestDB`;
CREATE DATABASE IF NOT EXISTS `TestDB`;
USE `TestDB`;
CREATE TABLE IF NOT EXISTS `Person`;

CREATE TABLE `Person` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `age` SMALLINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `update` TIMESTAMP NOT NULL)
 ENGINE=InnoDB;
