syntax = "proto3";

package stellar_post.notify;

import "base.proto";

// 启用C++通用服务代码生成
option cc_generic_services = true;

enum NotifyType {
  CRONY_ADD_APPLY_NOTIFY = 0;
  CRONY_ADD_PROCESS_NOTIFY = 1;
  CHAT_SESSION_CREATE_NOTIFY = 2;
  CHAT_MESSAGE_NOTIFY = 3;
  CRONY_REMOVE_NOTIFY = 4;
}
message NotifyCronyAddApply {
  base.UserInfo user_info = 1;//申请人信息
}
message NotifyCronyAddProcess {
  bool agree = 1;
  base.UserInfo user_info = 2;//处理人信息
}
message NotifyCronyRemove {
  string user_id = 1;//删除自己的用户 ID
}
message NotifyNewChatSession {
  base.ChatSessionInfo chat_session_info = 1;//新建会话信息
}
message NotifyNewMessage {
  base.MessageInfo message_info = 1;//新消息
}
message NotifyMessage {
  optional string notify_event_id = 1;//通知事件操作 id（有则填无则忽略）
  NotifyType notify_type = 2;//通知事件类型
  oneof notify_remarks { //事件备注信息
    NotifyCronyAddApply crony_add_apply = 3;
    NotifyCronyAddProcess crony_process_result = 4;
    NotifyCronyRemove crony_remove = 7;
    NotifyNewChatSession new_chat_session_info = 5;//会话信息
    NotifyNewMessage new_message_info = 6;//消息信息
  }
}