#pragma once

// C++
#include <iostream>
#include <string>
#include <vector>
#include <queue>
#include <unordered_map>
#include <functional>
#include <memory>
#include <thread>
#include <chrono>
#include <deque>
#include <atomic>
#include <mutex>
// C
#include <cerrno>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cassert>
// system
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <time.h>
#include <signal.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/epoll.h>
// other
#include <jsoncpp/json/json.h>