/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
CREATE DATABASE IF NOT EXISTS `stellar_post`;
USE `stellar_post`;

DROP TABLE IF EXISTS `crony_apply`;

CREATE TABLE `crony_apply` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `applicant_id` varchar(64) NOT NULL,
  `receiver_id` varchar(64) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `event_id_i`
  ON `crony_apply` (`event_id`);

CREATE INDEX `applicant_id_i`
  ON `crony_apply` (`applicant_id`);

CREATE INDEX `receiver_id_i`
  ON `crony_apply` (`receiver_id`);

