/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
CREATE DATABASE IF NOT EXISTS `stellar_post`;
USE `stellar_post`;

DROP TABLE IF EXISTS `message`;

CREATE TABLE `message` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` varchar(64) NOT NULL,
  `chat_session_id` varchar(64) NOT NULL,
  `from_user_id` varchar(64) NOT NULL,
  `generate_time` TIMESTAMP NOT NULL,
  `message_type` TINYINT UNSIGNED NOT NULL,
  `content` TEXT NULL,
  `file_id` varchar(64) NULL,
  `file_name` varchar(127) NULL,
  `file_size` BIGINT UNSIGNED NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `message_id_i`
  ON `message` (`message_id`);

CREATE INDEX `chat_session_id_i`
  ON `message` (`chat_session_id`);

