# 不能带 ""

# rpc
# 服务注册中心地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-registryHost=http://127.0.0.1:2379
# 服务监控根目录
-baseService=/service
# 当前实例名称
-instanceName=/file_service/
# 服务实例外部访问地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-accessHost=127.0.0.1:16424
# 文件保存路径
-storagePath=./data/

# rpc
# rpc 服务默认监听端口
-rpc_linstenPort=16424
# rpc 空闲超时时间
-rpc_idleTimeout=1
# rpc IO 线程数量
-rpc_numThreads=9

# 是否启用守护进程
-use_daemon=true
# 守护进程工作目录
-work_dir=""

# -flagfile=${file_name}