# etcd
# 服务注册中心地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-registryHost=http://127.0.0.1:2379
# 服务监控根目录
-baseService=/service
# 文件服务名称
-fileService=/service/file_service
# 用户服务名称
-userService=/service/user_service
# 消息服务名称
-msgService=/service/message_service
# 消息转发服务名称
-transmiteService=/service/transmite_service
# 语音服务名称
-speechService=/service/speech_service
# 好友服务名称
-cronyService=/service/crony_service

# port(websocket & http)
# websocket 服务默认监听端口
-websocket_port=16421
# http 服务默认监听端口
-http_port=16422

# redis
# redis 主机地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-redis_host=127.0.0.1
# redis 端口
-redis_port=6379
# redis 数据库编号(默认0)
-redis_db=0
# redis keepAlive
-redis_keepAlive=true

# daemon
# 是否启用守护进程
-use_daemon=true
# 守护进程工作目录
-work_dir=""

# -flagfile=${file_name}