# etcd
# 服务注册中心地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-registryHost=http://127.0.0.1:2379
# 服务监控根目录
-baseService=/service
# 用户服务名称
-userService=/service/user_service
# 当前实例名称
-instanceName=/transmite_service/instance
# 服务实例外部访问地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-accessHost=127.0.0.1:16426

# rpc
# rpc 服务默认监听端口
-rpc_linstenPort=16426
# rpc 空闲超时时间
-rpc_idleTimeout=-1
# rpc IO 线程数量
-rpc_numThreads=4

# mysql
# mysql message 数据库用户名
-user=stellar_post
# mysql message's password
-pswd=stellar_post
# host -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-host=127.0.0.1
# database
-database=stellar_post
# cset
-cset=utf8
# port
-port=0
# connPoolCount
-connPoolCount=4

# RabbitMq
# rabbitmq user
-mq_user=stellar_post
# rabbitmq user's password
-mq_passwd=stellar_post
# rabbitmq host -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-mq_host=127.0.0.1:5672
# message persistence rabbitmq's exchangeName
-mq_exchangeName=msgExchange
# message persistence rabbitmq's queueName
-mq_queueName=msgQueue
# message persistence rabbitmq's bindingKey
-mq_bindingKey=msgQueue

# daemon
# 是否启用守护进程
-use_daemon=true
# 守护进程工作目录
-work_dir=""

# -flagfile=${file_name}