# etcd
# 服务注册中心地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-registryHost=http://127.0.0.1:2379
# 服务监控根目录
-baseService=/service
# 当前实例名称
-instanceName=/user_service/instance
# 服务实例外部访问地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-accessHost=127.0.0.1:16425

# rpc
# rpc 服务默认监听端口
-rpc_linstenPort=16425
# rpc 空闲超时时间
-rpc_idleTimeout=-1
# rpc IO 线程数量
-rpc_numThreads=4

# mysql
# mysql message 数据库用户名
-user=stellar_post
# mysql message's password
-pswd=stellar_post
# host -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-host=127.0.0.1
# database
-database=stellar_post
# cset
-cset=utf8
# port
-port=0
# connPoolCount
-connPoolCount=4

# elasticsearch
# elastic search url  -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-esHost=http://127.0.0.1:9200/

# dms
# DMS 平台访问密钥 ID
-keyId=your_access_key_id
# DMS 平台访问密钥 Secret
-keySecret=your_access_key_secret

# redis
# redis 主机地址 -- 改为 IP 地址, 用 docker 不能本地环回(部署在一个机子, 分布式改为各自机子的 IP 即可)
-redis_host=127.0.0.1
# redis 端口
-redis_port=6379
# redis 数据库编号(默认0)
-redis_db=0
# redis keepAlive
-redis_keepAlive=true

# daemon
# 是否启用守护进程
-use_daemon=true
# 守护进程工作目录
-work_dir=""

# -flagfile=${file_name}