/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

/* USE database */

DROP TABLE IF EXISTS `Classes`;

DROP TABLE IF EXISTS `Student`;

CREATE TABLE `Student` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `sn` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NULL,
  `class_id` BIGINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `sn_i`
  ON `Student` (`sn`);

CREATE INDEX `class_id_i`
  ON `Student` (`class_id`);

CREATE TABLE `Classes` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

